version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: local-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_mysql_database_name
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_user_password
    volumes:
      - mysql_data:/var/lib/mysql